name: harpia

services:
  harpia-ms-telemetria:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - MONGODB_DATABASE_URL=${MONGODB_DATABASE_URL}
      - MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_VIRTUAL_HOST=${RABBITMQ_VIRTUAL_HOST}
      - RABBITMQ_USE_SSL=${RABBITMQ_USE_SSL}
      - RABBITMQ_VERIFY_HOSTNAME=${RABBITMQ_VERIFY_HOSTNAME}
      - RABBITMQ_KEYSTORE_PATH=${RABBITMQ_KEYSTORE_PATH}
      - RABBITMQ_KEYSTORE_PASS=${RABBITMQ_KEYSTORE_PASS}
      - RABBITMQ_TRUSTSTORE_PATH=${RABBITMQ_TRUSTSTORE_PATH}
      - RABBITMQ_TRUSTSTORE_PASS=${RABBITMQ_TRUSTSTORE_PASS}
      - MS_TELEMETRIA_QUEUE_NAME=${MS_TELEMETRIA_QUEUE_NAME}
      - MS_EXCHANGE_NAME=${MS_EXCHANGE_NAME}
      - ROUTING_KEY_TELEMETRIA=${ROUTING_KEY_TELEMETRIA}
      - FLYWEIGHT_EQUIPAMENTO_MAX=${FLYWEIGHT_EQUIPAMENTO_MAX}
      - GRPC_CCO_SERVER_HOST=${GRPC_CCO_SERVER_HOST}
      - GRPC_CCO_SERVER_PORT=${GRPC_CCO_SERVER_PORT}
      - GRPC_API_KEY=${GRPC_API_KEY}
      - FALLBACK_URL=${FALLBACK_URL}