name: harpia

services:
  harpia-ms-telemetria:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - CCO_URL=${CCO_URL}
      - CCO_USER_INFO_ENDPOINT=${CCO_USER_INFO_ENDPOINT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - FLYWEIGHT_EQUIPAMENTO_MAX=${FLYWEIGHT_EQUIPAMENTO_MAX}
      - FRONTEND_URL=${FRONTEND_URL}
      - MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME}
      - MONGODB_DATABASE_URL=${MONGODB_DATABASE_URL}
      - MS_EXCHANGE_NAME=${MS_EXCHANGE_NAME}
      - MS_TELEMETRIA_QUEUE_NAME=${MS_TELEMETRIA_QUEUE_NAME}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - ROUTING_KEY_TELEMETRIA=${ROUTING_KEY_TELEMETRIA}
      - SERVER_PORT=${SERVER_PORT}