spring.application.name=harpia-ms-telemetria

### Persistencia
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

mongodb.database.url=${MONGODB_DATABASE_URL}
mongodb.database.name=${MONGODB_DATABASE_NAME}
### Persistencia

### RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.virtual-host=${RABBITMQ_VIRTUAL_HOST}
spring.rabbitmq.ssl.enabled=${RABBITMQ_USE_SSL}
spring.rabbitmq.ssl.verify-hostname=${RABBITMQ_VERIFY_HOSTNAME}
spring.rabbitmq.ssl.key-store=file:${RABBITMQ_KEYSTORE_PATH}
spring.rabbitmq.ssl.key-store-password=${RABBITMQ_KEYSTORE_PASS}
spring.rabbitmq.ssl.key-store-type=PKCS12
spring.rabbitmq.ssl.trust-store=file:${RABBITMQ_TRUSTSTORE_PATH}
spring.rabbitmq.ssl.trust-store-password=${RABBITMQ_TRUSTSTORE_PASS}
spring.rabbitmq.ssl.trust-store-type=JKS

ms-telemetria.queue.name=${MS_TELEMETRIA_QUEUE_NAME}
ms.exchange.name=${MS_EXCHANGE_NAME}
routing-key.telemetria=${ROUTING_KEY_TELEMETRIA}
### RabbitMQ

flyweight.equipamento.max=${FLYWEIGHT_EQUIPAMENTO_MAX}

### gRPC
grpc-cco.server.host=${GRPC_CCO_SERVER_HOST}
grpc-cco.server.port=${GRPC_CCO_SERVER_PORT}
### gRPC