spring.application.name=harpia-ms-telemetria

server.port=${SERVER_PORT}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

frontend.url=${FRONTEND_URL}

cco.url=${CCO_URL}

rabbitmq.exchange.name=${RABBITMQ_EXCHANGE_NAME}
rabbitmq.ms.queue.name=${RABBITMQ_MS_QUEUE_NAME}
rabbitmq.ms.prefetch=${RABBITMQ_MS_PREFETCH}

mongodb.database.url=${MONGODB_DATABASE_URL}
mongodb.database.name=${MONGODB_DATABASE_NAME}
