server.port=${SERVER_PORT}

spring.application.name=harpia-ms-telemetria

### Persistência
mongodb.database.url=${MONGODB_DATABASE_URL}
mongodb.database.name=${MONGODB_DATABASE_NAME}
### Persistência

### RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

ms-telemetria.queue.name=${MS_TELEMETRIA_QUEUE_NAME}
ms.exchange.name=${MS_EXCHANGE_NAME}
telemetria.routing-key=${TELEMETRIA_ROUTING_KEY}
### RabbitMQ

### CCO
cco.url=${CCO_URL}
cco.user-info-endpoint=${CCO_USER_INFO_ENDPOINT}
### CCO

### Frontend
frontend.url=${FRONTEND_URL}
### Frontend

flyweight.equipamento.max=${FLYWEIGHT_EQUIPAMENTO_MAX}